# Generated by Django 5.0.6 on 2024-07-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
                'ordering': ['idCategoria'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.CharField(max_length=10)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('correo', models.EmailField(blank=True, max_length=80, null=True, unique=True)),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreContacto', models.CharField(max_length=60)),
                ('correoArriendo', models.EmailField(blank=True, max_length=80, null=True)),
                ('mensaje', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('idArriendo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreArriendo', models.CharField(max_length=60)),
                ('apellidoArriendo', models.CharField(max_length=60)),
                ('correoArriendo', models.EmailField(blank=True, max_length=80, null=True)),
                ('celularArriendo', models.CharField(max_length=10)),
                ('cant_carpas_menor4', models.IntegerField(default=0)),
                ('cant_carpas_mayor4', models.IntegerField(default=0)),
                ('fecha_inicio_Arriento', models.DateField()),
                ('fecha_fin_Arriendo', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['id'],
            },
        ),
    ]
