# Generated by Django 5.0.6 on 2024-07-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_arriendo_cliente_remove_cliente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='cant_carpas_mayor4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='cant_carpas_menor4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='correoArriendo',
            field=models.EmailField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correoArriendo',
            field=models.EmailField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
