# Generated by Django 5.0.6 on 2024-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_arriendo_cant_carpas_mayor4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='cant_carpas_mayor4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='cant_carpas_menor4',
            field=models.IntegerField(default=1),
        ),
    ]
